version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - /var/jenkins_home

  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - jenkins